### ISSUE TITLE
WP-CLI ```wp user list``` returns an error

### ISSUE THREAD

**Issue by stunney** [bitnami/bitnami-docker-wordpress-nginx#41]
**Description**

WP-CLI ```wp user list``` returns an error

**Steps to reproduce the issue:**

1. Start the container
2. run  the following from the host
```
docker exec my_wordpress_1 wp user list --allow-root
```
3. Stack trace is dumped out

```
PHP Fatal error:  Uncaught Error: Call to undefined method WSAL_Settings::IsPhpErrorLoggingEnabled() in /bitnami/wordpress/wp-content/plugins/wp-security-audit-log/classes/Sensors/PhpErrors.php:61
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/wp-security-audit-log/classes/SensorManager.php(88): WSAL_Sensors_PhpErrors->HookEvents()
#1 /bitnami/wordpress/wp-content/plugins/wp-security-audit-log/wp-security-audit-log.php(1084): WSAL_SensorManager->HookEvents()
#2 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(287): WpSecurityAuditLog->init()
#3 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#4 /opt/bitnami/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action()
#5 /opt/bitnami/wordpress/wp-settings.php(557): do_action()
#6 phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('/opt/bitnami/wo...')
#7 phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#8 pha in /bitnami/wordpress/wp-content/plugins/wp-security-audit-log/classes/Sensors/PhpErrors.php on line 61
Fatal error: Uncaught Error: Call to undefined method WSAL_Settings::IsPhpErrorLoggingEnabled() in /bitnami/wordpress/wp-content/plugins/wp-security-audit-log/classes/Sensors/PhpErrors.php:61
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/wp-security-audit-log/classes/SensorManager.php(88): WSAL_Sensors_PhpErrors->HookEvents()
#1 /bitnami/wordpress/wp-content/plugins/wp-security-audit-log/wp-security-audit-log.php(1084): WSAL_SensorManager->HookEvents()
#2 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(287): WpSecurityAuditLog->init()
#3 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#4 /opt/bitnami/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action()
#5 /opt/bitnami/wordpress/wp-settings.php(557): do_action()
#6 phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('/opt/bitnami/wo...')
#7 phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#8 pha in /bitnami/wordpress/wp-content/plugins/wp-security-audit-log/classes/Sensors/PhpErrors.php on line 61
Error: There has been a critical error on this website.Learn more about debugging in WordPress. There has been a critical error on this website.
```

**Describe the results you expected:**

See the list of users in the wp_users table

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-65-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.941GiB
 Name: ubuntu-s-1vcpu-1gb-tor1-01
 ID: CXTF:FLDE:F7JP:2VLR:QW2A:BKV4:EISZ:7UC2:ZNST:NKN5:AZXF:YWOX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
DigitalOcean Droplet - Ubuntu 20.4 LTS x64, 2GB, 2CPU (Intel)

**Comment by marcosbc** [comment]
Hi @stunney, unfortunately I cannot reproduce this with the stock Bitnami chart for WordPress.

In your case, it seems like the `wp-security-audit-log` plugin which you installed is causing problems with `wp-cli`. Note that this plugin is not installed by default with the Bitnami chart.

This error has been reported to be happening with non-Bitnami installations as well, so I'd recommend you to either disable that plugin, or not to rely on `wp-cli`: https://wordpress.org/support/topic/fatal-error-uncaught-error-on-my-animation-website/

**Comment by stunney** [comment]
Disabling that plug-in has fixed the issue.

Thanks for taking the time to respond.
